'use client';

import { Sparkles } from "lucide-react";
import type { AIResult } from "@/types/scan";

interface Props {
  data: AIResult | null;
}

export function AISummaryCard({ data }: Props) {
  if (!data) return null;

  return (
    <div className="rounded-lg border border-zinc-800 bg-zinc-900/50 p-5">
      <div className="flex items-center gap-2 mb-4">
        <Sparkles className="h-4 w-4 text-[#00d4aa]" />
        <h3 className="text-sm font-medium text-zinc-200">AI Analysis</h3>
      </div>
      <div className="mb-4">
        <p className="text-sm text-zinc-300 leading-relaxed">{data.summary}</p>
        <p className="text-xs text-zinc-700 mt-2">This summary was generated by AI based on scan results.</p>
      </div>
    </div>
  );
}
